<template lang="pug">
  .page
    .b-page-content
      .b-page-section
        .container.m-short
          h1 Privacy policy
          ol
            li
              p iBookingNet endeavour to protect your privacy and assure the confidentiality of your data. iBookingNet would like to inform you of what data we store, how we use it and what it means for you to use our personalised services.
              p When logging on to our Internet offer we collect, process and use the IP address of your terminal as well as other information such as date, time, the called-up page and store this information. This data is not utilised except anonymously for statistical purposes and to optimise our Internet offers. We only store your personal data like name, physical and postal addresses, telephone number, fax number, eMail address etc. when you give them to us during a booking procedure.

            li
              p We collect, process and use your personal data exclusively to enable you to book and take up the desired rental properties, to create quotes and perform anonymous statistical analysis. Collecting and transferring data to government offices only occurs within imperative statutory provisions.

            li
              p The iBookingNet commits itself to protect the privacy of the traveller and assures that it will collect, process and use the personal data exclusively in accordance with the Bundesdatenschutzgesetz [German Data Protection Act], the Telemediengesetz [German Tele Media Act] and other relevant statutory provisions.

            li
              p The personal data is stored and processed on our servers exclusively at both the business location of iBookingNet.

            li
              p The company uses ‘Cookies’ to make the use of the website easier. When you reconnect to the website, the stored data is displayed again. The user data is not stored on the iBookingNet servers at any time. To allow the storage of the Cookies you must enable these in your Internet software (browser).

            li
              p The user has the rights afforded through the German Data Protection Act to gratuitous information regarding his personal data as well as to correction, deletion or blocking incorrect data. These rights should be exercised by way of mail or electronic mail to the contact person listed under item 8. The entitlement to correction could be in conflict with statutory provisions in particular regarding data for invoicing and accounting purposes.

            li
              p For payment the traveller will be connected to websites of payment services through hyperlinks. We would like to inform you that here further personal data will be collected, processed and used. The company does not assume any responsibility for this. The usage and data protection regulations of the payment services apply here exclusively.

            li The contact person for all questions and requests related to data protection as well as the exercise of the rights to access and correcting is:
              p iBookingNet
                br
                | 2300 Irving St
                br
                | San Francisco, CA USA
                br
                | eMail:&nbsp;
                a(href="mailto:mike@ibookingnet.com") mike@ibookingnet.com

            li
              p We thereby take your interests worthy of protection into consideration. In connection with the booking transaction, iBookingNet uses the encryption process SSL (Secure Socket Layer) to provide optimal protection from unauthorised access of your personal data and bank or credit card information transmitted through the Internet.

            li
              p This website uses Google Analytics, a web analytics service provided by Google, Inc. (“Google”). Google Analytics uses “cookies,” which are text files placed on your computer, to help the website analyze how users use the site. The information generated by the cookie about your use of the website will be transmitted to and stored by Google on servers in the United States. In case IP-anonymisation is activated on this Website, your IP address will be truncated within the area of Member States of the European Union or other parties to the Agreement on the European Economic Area. Only in exceptional cases the whole IP address will be first transferred to a Google server in the USA and truncated there. The IP-anonymisation is active on this Website. Google will use this information on behalf of the operator of this Website for the purpose of evaluating your use of the Website, compiling reports on Website activity for Website operators and providing them other services relating to Website activity and internet usage. The IP-address that your Browser conveys within the scope of Google Analytics will not be associated with any other data held by Google. You may refuse the use of cookies by selecting the appropriate settings on your browser, however please note that if you do this you may not be able to use the full functionality of this Website. You can also opt-out from being tracked by Google Analytics with effect for the future by downloading and installing Google Analytics Opt-out Browser Add-on for your current web browser: &nbsp;
                a(href="https://tools.google.com/dlpage/gaoptout?hl=en") https://tools.google.com/dlpage/gaoptout?hl=en
                | .
</template>

<script>
  export default {
    scrollToTop: true,
    head () {
      return {
        title: 'Cancellation Policy - iBookingNet'
      }
    }
  }
</script>
